"""Generate the cabin art for Please Remain Seated, in the workshop's own idiom.

    python pixel-workshop/make_cabin_textures.py             # write game/art/cabin-sprites.js
    python pixel-workshop/make_cabin_textures.py --preview   # also write cabin-preview.png
    python pixel-workshop/make_cabin_textures.py --json      # also write cabin-sprites.json

Everything here is an ASCII map plus a palette, the same shape as `sprites.json`, so `pixelmap.js`
draws it without knowing it is new. Three groups:

    tiles     16x16, top-down, nose to the left. Seats, aisle, galley, bins, doors, walls.
    entities  16x16, drawn over a tile. People, fire at four intensities, smoke, the player.
    items     16x16 icons for the loadout, in the item idiom: outline, three tones, a highlight.

Why the maps are written out and not drawn
------------------------------------------

The same reason the modpack does it: a person is one map and sixty palettes. Every passenger on
Flight 447 is `pax` with a skin, a hair and a shirt colour swapped in, so no passenger can drift
away from the others and adding one is three hex values in `passengers.js`. Fire is one map at
four sizes rather than four drawings, so the four read as the same fire growing. The seven
miniature spirit bottles are `mini_bottle` seven times, which is exactly the trick `sprites.json`
plays with the science flasks, and the joke lands better when the gin and the whisky are visibly
the same bottle.

Why the output is a .js and not a .json
---------------------------------------

The game has to open by double-clicking `index.html`. A `file://` page may not `fetch` a sibling
file and may not load an ES module, so the art ships as a classic script that assigns a global,
the way `demo.html` inlines its copy. `--json` writes the JSON too, for `pixelmap.js` users and
for diffing against this file.

Reading the maps
----------------

Top-down, so a seat is a cushion with its backrest at the nose end of the cell and the aisle side
open, and a person is a head with shoulders under it. `.` is transparent and every entity is drawn
over a floor tile, so the walls are the only opaque things. A key missing from a palette draws
magenta, which is how a hole is found before it is shipped.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, os.pardir)
OUT_DIR = os.path.join(ROOT, "game", "art")


def m(text):
    """A map written as one multi-line string, blank edge lines dropped, short rows padded."""
    lines = [line.rstrip() for line in text.split("\n")]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    width = max(len(line) for line in lines)
    return [line.ljust(width, ".") for line in lines]


SPRITES = {}


def sprite(name, rows, palette):
    SPRITES[name] = {"rows": rows, "palette": palette, "source": "make_cabin_textures.py"}


def variant(name, base, palette_override):
    """One map, another palette: the family trick, so members cannot drift apart."""
    src = SPRITES[base]
    SPRITES[name] = {
        "rows": src["rows"],
        "palette": {**src["palette"], **palette_override},
        "source": "make_cabin_textures.py",
    }


# ---------------------------------------------------------------------------------------------
# Tiles. The floor is drawn under everything, so a tile above it may have air in it.
# ---------------------------------------------------------------------------------------------

# Airline carpet: a dark blue-grey with a fleck, because it has to hide everything.
sprite("floor_carpet", m("""
cccccccccccccccc
ccccfcccccccccfc
ccccccccfccccccc
cfcccccccccccccc
ccccccccccccfccc
ccfccccccccccccc
cccccfccccccccfc
cccccccccccccccc
ccccccccfccccccc
cfccccccccccfccc
cccccccccccccccc
ccccfccccccccccc
cccccccccfcccccc
cfcccccccccccccc
ccccccfccccccfcc
cccccccccccccccc
"""), {"c": "#2f3746", "f": "#39424f"})

# The aisle, worn lighter by three hundred flights a year.
sprite("floor_aisle", m("""
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aawaaaaaaaaaaaaa
aaaaaaaaaawaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
awaaaaaaaaaaaawa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaawaaaaaaaa
aaaaaaaaaaaaaaaa
aaawaaaaaaaaaaaa
aaaaaaaaaaaawaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
"""), {"a": "#3b4454", "w": "#47515f"})

# A seat from above: headrest at the nose end, cushion, an armrest either side.
# The blue is the airline's blue, which is the same blue as every airline's blue.
sprite("seat", m("""
.dddddddddddddd.
.dhhhhhhhhhhhhd.
.dhbbbbbbbbbbhd.
ddbbbbbbbbbbbbdd
dabbllllllllbbad
dabbllllllllbbad
dabblllllllllbad
dabblllllllllbad
dabblllllllllbad
dabblllllllllbad
dabbllllllllbbad
dabbllllllllbbad
ddbbbbbbbbbbbbdd
.dbbbbbbbbbbbbd.
.dddddddddddddd.
................
"""), {"d": "#1a2230", "h": "#39445c", "b": "#2c3a55", "l": "#3f5177", "a": "#4b5468"})

# The same seat scorched, and the same seat gone: one map, three states of the day.
variant("seat_scorched", "seat", {"h": "#3a3a3a", "b": "#2a2622", "l": "#453d34", "a": "#3c372f"})
variant("seat_burnt", "seat", {"d": "#141414", "h": "#242020", "b": "#1c1918",
                               "l": "#2a2422", "a": "#241f1c"})

# The overhead locker, seen from above as the lip over the seats: closed, and open.
sprite("bin_closed", m("""
mmmmmmmmmmmmmmmm
mhhhhhhhhhhhhhhm
mhllllllllllllhm
mhllllllllllllhm
mhllllllllllllhm
mhllllllllllllhm
mmmmmmmmmmmmmmmm
mkkkkkkkkkkkkkkm
mmmmmmmmmmmmmmmm
"""), {"m": "#4d525e", "h": "#8d94a2", "l": "#6e7684", "k": "#343842"})

sprite("bin_open", m("""
mmmmmmmmmmmmmmmm
mhhhhhhhhhhhhhhm
mmmmmmmmmmmmmmmm
.vvvvvvvvvvvvvv.
.vggggggggggggv.
.vgbbbbggbbbbgv.
.vgbbbbggbbbbgv.
.vggggggggggggv.
.vvvvvvvvvvvvvv.
"""), {"m": "#4d525e", "h": "#8d94a2", "v": "#1b1e25", "g": "#2a2f38", "b": "#3b414d"})

# The wall, which is the only opaque tile in the cabin, and the window in it.
sprite("wall", m("""
pppppppppppppppp
pssssssssssssssp
pssssssssssssssp
pppppppppppppppp
pssssssssssssssp
pssssssssssssssp
pppppppppppppppp
pssssssssssssssp
pssssssssssssssp
pppppppppppppppp
pssssssssssssssp
pssssssssssssssp
pppppppppppppppp
pssssssssssssssp
pssssssssssssssp
pppppppppppppppp
"""), {"p": "#5b6270", "s": "#767e8d"})

sprite("window", m("""
pppppppppppppppp
pssssssssssssssp
psspppppppppsssp
pspwwwwwwwwwpssp
pspwccccccwwpssp
pspwcccccccwpssp
pspwcccccccwpssp
pspwcccccccwpssp
pspwcccccccwpssp
pspwwcccccwwpssp
pspwwwwwwwwwpssp
psspppppppppsssp
pssssssssssssssp
pssssssssssssssp
pppppppppppppppp
"""), {"p": "#5b6270", "s": "#767e8d", "w": "#3c4350", "c": "#9fd4f2"})

# The galley: a steel monument to trolleys, at both ends of the aeroplane.
sprite("galley", m("""
dddddddddddddddd
dhhhhhhhhhhhhhhd
dhllllddllllllhd
dhllllddllllllhd
dhllllddllllllhd
dddddddddddddddd
dhllllddllllllhd
dhllllddllllllhd
dhllllddllllllhd
dddddddddddddddd
dhllllddllllllhd
dhllllddllllllhd
dhllllddllllllhd
dhhhhhhhhhhhhhhd
dddddddddddddddd
"""), {"d": "#3f444d", "h": "#aeb6c2", "l": "#858d9a"})

# The lavatory door, with the little sign that says whether the day can get worse.
sprite("lav_door", m("""
dddddddddddddddd
dlllllllllllllld
dlhhhhhhhhhhhhld
dlhllllllllllhld
dlhllllllllllhld
dlhllllggllllhld
dlhllllggllllhld
dlhllllllllllhld
dlhllllllllllhld
dlhllllllllllhld
dlhllllllllllhld
dlhhhhhhhhhhhhld
dlllllllllllllld
dddddddddddddddd
"""), {"d": "#3a3f48", "l": "#7b838f", "h": "#949cab", "g": "#2f7d4f"})

# An exit door, the handle picked out because it is the only part that matters.
sprite("exit_door", m("""
dddddddddddddddd
dlllllllllllllld
dlhhhhhhhhhhhhld
dlhmmmmmmmmmmhld
dlhmmmmmmmmmmhld
dlhmyyyyyyyymhld
dlhmykkkkkkymhld
dlhmyyyyyyyymhld
dlhmmmmmmmmmmhld
dlhmmmmmmmmmmhld
dlhhhhhhhhhhhhld
dlllllllllllllld
dddddddddddddddd
"""), {"d": "#2f343c", "l": "#6d757f", "h": "#8b93a0", "m": "#5a626d",
        "y": "#e8c53a", "k": "#22242a"})

# The cockpit door. Reinforced, locked, and it stays that way.
sprite("cockpit_door", m("""
kkkkkkkkkkkkkkkk
kmmmmmmmmmmmmmmk
kmhhhhhhhhhhhhmk
kmhssssssssssHmk
kmhssssssssssHmk
kmhsskkkkkkssHmk
kmhsskrrrrkssHmk
kmhsskkkkkkssHmk
kmhssssssssssHmk
kmhssssssssssHmk
kmhhhhhhhhhhhhmk
kmmmmmmmmmmmmmmk
kkkkkkkkkkkkkkkk
"""), {"k": "#232830", "m": "#454c57", "h": "#7e8794", "s": "#5f6773",
        "H": "#8e97a4", "r": "#c23a2e"})

# The bulkhead, and the flat panel a fire likes to live behind.
sprite("bulkhead", m("""
kkkkkkkkkkkkkkkk
klllllllllllllk.
kllhhhhhhhhhhlk.
kllhmmmmmmmmhlk.
kllhmmmmmmmmhlk.
kllhmmmmmmmmhlk.
kllhmmmmmmmmhlk.
kllhmmmmmmmmhlk.
kllhmmmmmmmmhlk.
kllhhhhhhhhhhlk.
klllllllllllllk.
kkkkkkkkkkkkkkkk
"""), {"k": "#2a2f37", "l": "#6a727e", "h": "#838b98", "m": "#727a86"})


# ---------------------------------------------------------------------------------------------
# Entities. Drawn over a tile, so they are mostly air.
# ---------------------------------------------------------------------------------------------

# People.
#
# Sixty-one faces out of one map. The body below has three colours in it that every passenger
# overrides - hair, skin, shirt - and five more that are the face: the eyes, the brow, the mouth,
# the lids, and `g`, which is the hair that comes down the sides of the head. None of those five
# is drawn as a colour anybody chose. The renderer works them out from the skin, so the eyes of
# the palest person on board and the eyes of the darkest are both eyes, and neither is a smudge.
#
# `g` is the trick worth knowing. Its pixels are on the outside of the face, where the skin used
# to be, so setting `g` to the skin colour gives short hair and setting it to the hair colour
# gives long hair. Two heads, one map, and the choice is a palette entry rather than a drawing.
#
# The expressions are the same body with five pixels moved, because a cabin that is frightened
# has to be visible as a cabin that is frightened and there is no meter for that. The face box is
# rows 5-9, columns 3-12, and a `~` in a patch means "leave the body alone".

PAX_BODY = m("""
................
................
.....hhhhhh.....
....hhhhhhhh....
....hssssssh....
...ghssssssshg..
...gssssssssg...
..cgssssssssgc..
..ccgssssssgcc..
.cccsssssssccccc
.ccccccccccccccc
..cccccccccccc..
...cccccccccc...
....cccccccc....
................
................
""")

# The same person slumped, which the game needs sixty-one of as well.
PAX_DOWN_BODY = m("""
................
................
................
................
...hhhh.........
..hhssshh.......
..hgssssgh......
..ssssssssccc...
..sssssscccccc..
...sscccccccccc.
....cccccccccccc
.....cccccccccc.
......cccccccc..
................
................
................
""")

# A smaller body for the people on board who are not adults: a narrower head on narrower
# shoulders, in the same face box, so a child and their parent are one drawing at two sizes.
CHILD_BODY = m("""
................
................
................
.....hhhhhh.....
....hhhhhhhh....
....ghssssgh....
....gssssssg....
...cgssssssgc...
...ccgssssgcc...
...cccssssccc...
...cccccccccc...
....cccccccc....
.....cccccc.....
................
................
................
""")

# The face. Defaults are worked out from the default skin, and every one of them is overridden
# per person by the renderer; they exist so the sprite is honest on its own in the gallery.
FACE_PALETTE = {"e": "#413024", "b": "#634a37", "m": "#564030", "l": "#9c7457", "g": "#d9a279"}

# rows 5..9 of the body, columns 3..12. Amount of dark on a face is the whole readout: a calm
# cabin is pale and a frightened one is not, and no number anywhere says so.
FACES = {
    "":          ["~~~~~~~~~~",
                  "~~ee~~ee~~",
                  "~~~~~~~~~~",
                  "~~~~mm~~~~",
                  "~~~~~~~~~~"],
    "_relieved": ["~~~~~~~~~~",
                  "~~ee~~ee~~",
                  "~~~m~~m~~~",
                  "~~~~mm~~~~",
                  "~~~~~~~~~~"],
    "_worried":  ["~~bb~~bb~~",
                  "~~ee~~ee~~",
                  "~~~~~~~~~~",
                  "~~~mmmm~~~",
                  "~~~~~~~~~~"],
    "_afraid":   ["~~bb~~bb~~",
                  "~~ee~~ee~~",
                  "~~~~~~~~~~",
                  "~~~mmmm~~~",
                  "~~~~mm~~~~"],
    "_asleep":   ["~~~~~~~~~~",
                  "~~ll~~ll~~",
                  "~~~~~~~~~~",
                  "~~~~ll~~~~",
                  "~~~~~~~~~~"],
}

# A child's head is narrower, so the same five patches lose their outer pixel and the eyes end up
# one pixel each and further apart, which is what a child's face does anyway.
CHILD_FACES = {
    "":          ["~~~~~~~~~~",
                  "~~~e~~e~~~",
                  "~~~~~~~~~~",
                  "~~~~mm~~~~",
                  "~~~~~~~~~~"],
    "_relieved": ["~~~~~~~~~~",
                  "~~~e~~e~~~",
                  "~~~m~~m~~~",
                  "~~~~mm~~~~",
                  "~~~~~~~~~~"],
    "_worried":  ["~~~b~~b~~~",
                  "~~~e~~e~~~",
                  "~~~~~~~~~~",
                  "~~~mmmm~~~",
                  "~~~~~~~~~~"],
    "_afraid":   ["~~~b~~b~~~",
                  "~~~e~~e~~~",
                  "~~~~~~~~~~",
                  "~~~mmmm~~~",
                  "~~~~mm~~~~"],
    "_asleep":   ["~~~~~~~~~~",
                  "~~~l~~l~~~",
                  "~~~~~~~~~~",
                  "~~~~ll~~~~",
                  "~~~~~~~~~~"],
}

# Lying down is a profile, so it gets one eye's worth of face and no expressions: the two states
# that use it are unconscious and being carried, and neither is doing much with a brow.
DOWN_FACES = {
    "_down": ["~~~~~~~~~~",      # out cold: the lid shut, the mouth slack and open
              "~~~ll~~~~~",
              "~~~~~mm~~~",
              "~~~~~~~~~~",
              "~~~~~~~~~~"],
    "_low":  ["~~~~~~~~~~",      # awake and low: crouching, or in somebody's arms
              "~~~ee~~~~~",
              "~~~~~mm~~~",
              "~~~~~~~~~~",
              "~~~~~~~~~~"],
}


def face(body, patch, y0=5, x0=3):
    """One body, one five-row patch over the face box. `~` keeps whatever the body had."""
    rows = [list(r) for r in body]
    for dy, line in enumerate(patch):
        for dx, ch in enumerate(line):
            if ch == "~":
                continue
            rows[y0 + dy][x0 + dx] = ch
    return ["".join(r) for r in rows]


PEOPLE_PALETTE = {"h": "#2b2118", "s": "#d9a279", "c": "#4a5a86", **FACE_PALETTE}

for suffix, patch in FACES.items():
    sprite("pax" + suffix, face(PAX_BODY, patch), PEOPLE_PALETTE)
for suffix, patch in CHILD_FACES.items():
    sprite("child" + suffix, face(CHILD_BODY, patch, y0=5, x0=3), PEOPLE_PALETTE)
# Nobody gets a child-sized version of these two: a person on the floor is a profile with one
# eye in it, and shrinking that produces a smudge rather than a smaller child.
for suffix, patch in DOWN_FACES.items():
    sprite("pax" + suffix, face(PAX_DOWN_BODY, patch, y0=5, x0=2), PEOPLE_PALETTE)

# You. A ring drawn under the body so you can find yourself in the smoke.
sprite("player_ring", m("""
....rrrrrrrr....
..rr........rr..
.r............r.
r..............r
r..............r
................
................
................
................
................
r..............r
r..............r
.r............r.
..rr........rr..
....rrrrrrrr....
"""), {"r": "#ffd54a"})

# The crew, in the airline's jacket, and the purser with the darker one.
variant("crew", "pax", {"c": "#20304e", "h": "#3a2c1e"})
variant("purser", "pax", {"c": "#141c30", "h": "#5a4630"})


# Fire, one map at four intensities. Orange outside, yellow within, white at the heart, which is
# the furnace flame's palette from make_gui_textures.py because it is the right one.
FIRE_PALETTE = {"o": "#ff7a10", "y": "#ffe02a", "w": "#fffce0", "d": "#a8360a"}

sprite("fire_1", m("""
................
................
................
................
................
................
.......o........
......ooo.......
......oyo.......
.....ooyoo......
.....oyyyo......
.....dooood.....
......ddd.......
................
................
................
"""), FIRE_PALETTE)

sprite("fire_2", m("""
................
................
................
.......o........
......oo.....o..
......ooo...oo..
.....oooo..ooo..
.....ooyooooooo.
....ooyyyoooooo.
....oyywwyyoooo.
....oyywwyyoooo.
....doyyyyyood..
.....dooooood...
......dddddd....
................
................
"""), FIRE_PALETTE)

sprite("fire_3", m("""
................
.......o........
......oo....o...
.....ooo...oo...
.....ooo..ooo...
....oooo.oooo...
....ooooooooo.o.
...oooyooooooooo
...ooyyyoooooooo
..ooyywwyyoooooo
..oyywwwwyyooooo
..oyywwwwyyooooo
..doyyyyyyyoood.
...dooooooooodd.
....dddddddddd..
......dddd......
"""), FIRE_PALETTE)

sprite("fire_4", m("""
....o....o......
...oo...oo...o..
...ooo.ooo..oo..
..oooo.oooo.ooo.
..ooooooooooooo.
.ooooooooooooooo
.oooyyoooooooooo
.ooyyyyyoooooooo
ooyywwwyyooooooo
ooywwwwwywoooooo
oyywwwwwwwyooooo
oyywwwwwwwyyoooo
doyywwwwwyyyoood
ddoyyyyyyyyyoodd
.ddooooooooooddd
..dddddddddddd..
"""), FIRE_PALETTE)

# Embers: what suppression leaves behind, and where it all starts again from.
sprite("ember", m("""
................
................
................
................
................
................
................
......e.........
.....ede...e....
....edkde.ede...
.....ede...e....
......e.........
................
................
................
................
"""), {"e": "#ff8c1a", "d": "#7a2b06", "k": "#ffd06a"})

# Smoke, three densities. The last one is what the cabin looks like when you cannot see the seat
# in front of you, which happens sooner than anybody expects.
sprite("smoke_1", m("""
................
....gg....gg....
...gggg..gggg...
...gggg..gggg...
....gg....gg....
................
..gg....gg......
.gggg..gggg.....
.gggg..gggg..gg.
..gg....gg..gggg
............gggg
.....gg......gg.
....gggg........
....gggg........
.....gg.........
................
"""), {"g": "#7b7f88"})

sprite("smoke_2", m("""
..gggg..gggg..gg
gggggggggggggggg
gggggggg.ggggggg
gggg.gggggggg.gg
.gggggggg.gggggg
gg.ggggggggg.ggg
ggggg.gggggggggg
.ggggggg.gggggg.
gggg.gggggggg.gg
ggggggg.gggggggg
.gg.gggggggg.ggg
gggggggg.gggggg.
ggg.gggggggg.ggg
.gggggggg.gggggg
gggg.ggggggggggg
gggggggg.gggggg.
"""), {"g": "#63666e"})

sprite("smoke_3", m("""
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
gggggggggggggggg
"""), {"g": "#3e4046"})

# The mask that drops from the ceiling, drawn on anyone wearing one.
sprite("mask_on", m("""
................
................
................
................
................
.....yyyyyy.....
....yyyyyyyy....
....yywwwwyy....
....yywwwwyy....
.....yyyyyy.....
......y..y......
.....t....t.....
................
................
................
................
"""), {"y": "#ffd93b", "w": "#fff6cf", "t": "#b8952a"})

# The marker for a passenger who is accounted for, and the one for a passenger who is not.
sprite("mark_saved", m("""
................
................
..............g.
.............gg.
............gg..
.g.........gg...
.gg.......gg....
..gg.....gg.....
...gg...gg......
....gg.gg.......
.....ggg........
......g.........
................
................
................
................
"""), {"g": "#5fd67a"})

sprite("mark_lost", m("""
................
................
..r..........r..
..rr........rr..
...rr......rr...
....rr....rr....
.....rr..rr.....
......rrrr......
......rrrr......
.....rr..rr.....
....rr....rr....
...rr......rr...
..rr........rr..
..r..........r..
................
................
"""), {"r": "#d4483a"})


# ---------------------------------------------------------------------------------------------
# Items. Sixteen pixels, an outline, three tones and a highlight: the item idiom.
# ---------------------------------------------------------------------------------------------

# The halon bottle the crew have and you do not. Red, because everything that works is red.
sprite("extinguisher", m("""
.......kk.......
......khhk......
.....kbbbbk.....
....kbhhhhbk....
...kbbbbbbbbk...
...kdrrrrrrdk...
...kdrhhrrrdk...
...kdrhhrrrdk...
...kdrrrrrrdk...
...kdrwwwwrdk...
...kdrwwwwrdk...
...kdrrrrrrdk...
...kdrrrrrrdk...
...kddddddddk...
....kkkkkkkk....
................
"""), {"k": "#2a1210", "r": "#c8322a", "h": "#f0736a", "d": "#8c1f19",
        "w": "#e8e2d4", "b": "#7b828c"})

variant("extinguisher_water", "extinguisher", {"r": "#3f7fc4", "h": "#8dc3ee", "d": "#26558c"})
variant("extinguisher_foam", "extinguisher", {"r": "#d8d3c2", "h": "#fbf8ee", "d": "#9a9484"})
variant("extinguisher_spent", "extinguisher", {"r": "#5c5c5c", "h": "#7d7d7d", "d": "#3a3a3a"})

# The drop-down oxygen mask, with its hose and its useless-looking little bag.
sprite("oxygen_mask", m("""
.......tt.......
.......tt.......
......tttt......
.....t....t.....
....kkkkkkkk....
...kyyyyyyyyk...
..kyywwwwwwyyk..
..kywwwwwwwwyk..
..kywwwwwwwwyk..
..kyywwwwwwyyk..
...kyyyyyyyyk...
....kyyyyyyk....
.....kyyyyk.....
......kkkk......
................
................
"""), {"k": "#6e5310", "y": "#f5cd3a", "w": "#fff4d0", "t": "#a08a3c"})

# A folded blanket, and the same blanket after four seconds in a lavatory sink.
sprite("blanket", m("""
................
..kkkkkkkkkkkk..
.khhhhhhhhhhhhk.
.kbbbbbbbbbbbbk.
.kbllllllllllbk.
.kbllllllllllbk.
.kkkkkkkkkkkkkk.
.kbllllllllllbk.
.kbllllllllllbk.
.kbllllllllllbk.
.kkkkkkkkkkkkkk.
.kbllllllllllbk.
.kbllllllllllbk.
.khhhhhhhhhhhhk.
..kkkkkkkkkkkk..
................
"""), {"k": "#1e2a3c", "h": "#5f7196", "b": "#2f3f5e", "l": "#43567c"})

variant("blanket_wet", "blanket", {"h": "#3d5f7a", "b": "#1c3040", "l": "#264456"})
variant("blanket_scorched", "blanket", {"h": "#4a4034", "b": "#2a231c", "l": "#3a3128"})

# The bottle of still water that will turn out to be your main weapon, which is the joke.
sprite("water_bottle", m("""
.......kk.......
.......kk.......
......kddk......
......kbbk......
.....kbwwbk.....
....kbwwwwbk....
....kbwwwwbk....
....kbwwwwbk....
....kbwwwwbk....
....kbwwwwbk....
....kbwwwwbk....
....kbwwwwbk....
....kbwwwwbk....
....kbbbbbbk....
.....kkkkkk.....
................
"""), {"k": "#2b3844", "b": "#7fb6d8", "w": "#cfe9f7", "d": "#4a7fa0"})

variant("water_bottle_empty", "water_bottle", {"b": "#8e9aa4", "w": "#c3ccd3", "d": "#66727c"})
variant("soda_can", "water_bottle", {"b": "#b8342c", "w": "#e8746a", "d": "#7d1e18"})

# The ice bucket from the galley: more water than the bottle, and heavier.
sprite("ice_bucket", m("""
................
..kkkkkkkkkkkk..
..khhhhhhhhhhk..
..kwiiwiiwiiwk..
..kiwwiwwiwwik..
..kwiiwiiwiiwk..
..khhhhhhhhhhk..
..klllllllllk...
...klllllllk....
...kllllllk.....
....klllllk.....
....kllllk......
....kkkkkk......
................
................
................
"""), {"k": "#2f363f", "h": "#b3bcc7", "l": "#8b95a1", "i": "#cfe6f4", "w": "#ffffff"})

# The galley coffee pot: hot, which is the wrong property for this problem.
sprite("coffee_pot", m("""
................
....kkkkkkk.....
....khhhhhk.....
...kkkkkkkkk....
...kbbbbbbbkk...
...kbcccccbkkk..
...kbcccccbk.k..
...kbcccccbk.k..
...kbcccccbkkk..
...kbcccccbk....
...kbcccccbk....
...kbbbbbbbk....
....kkkkkkk.....
................
................
................
"""), {"k": "#241a12", "h": "#6c5a48", "b": "#3f342a", "c": "#7a4a1e"})

# The crash axe. It is behind a panel on the flight deck and it is not for you.
sprite("crash_axe", m("""
............kk..
..........kkhk..
.........khhhk..
........khhhhk..
.......khhhhhk..
......khrrrrhk..
.....khrrrrrhk..
....khhrrrrhk...
....kbbhhhhk....
...kbbbk........
..kbbbk.........
..kbbk..........
.kbbk...........
.kbk............
.kk.............
................
"""), {"k": "#1c1a18", "h": "#b6bec8", "r": "#c4362c", "b": "#7a5228"})

# The smoke hood the crew keep for exactly this, sealed in its foil.
sprite("smoke_hood", m("""
................
....kkkkkkkk....
...kssssssssk...
..kssssssssssk..
..ksswwwwwwssk..
..kswwwwwwwwsk..
..kswwwwwwwwsk..
..ksswwwwwwssk..
..kssssssssssk..
..kssoooooosk...
..kssoooooosk...
..kssssssssssk..
...kssssssssk...
....kkkkkkkk....
................
................
"""), {"k": "#3a3a2e", "s": "#c9c2a6", "w": "#e9f3f8", "o": "#d8862c"})

# Fire gloves, which are the only reason you can hold anything.
sprite("fire_gloves", m("""
................
...kk...kk......
..khhk.khhk.....
..khhkkkhhk.....
.kkhhhhhhhkk....
.khhhhhhhhhk....
.khhhhhhhhhk....
.khyyyyyyyhk....
.khyyyyyyyhk....
.khhhhhhhhhk....
..khhhhhhhk.....
..kdddddddk.....
..kkkkkkkkk.....
................
................
................
"""), {"k": "#2a2018", "h": "#9c7a4a", "y": "#d8b46a", "d": "#5e4628"})

# The life vest, under your seat, of no use whatsoever at thirty-one thousand feet.
sprite("life_vest", m("""
................
...kkk....kkk...
..kyyyk..kyyyk..
..kyyyyyyyyyyk..
..kyyyyyyyyyyk..
..kyyyrrrryyyk..
..kyyyrrrryyyk..
..kyyyyyyyyyyk..
..kyyykkkkyyyk..
..kyyyk..kyyyk..
..kyyyk..kyyyk..
..kyyyk..kyyyk..
..kkkk....kkkk..
................
................
................
"""), {"k": "#5a4a10", "y": "#f2c02a", "r": "#c8362c"})

# The seat cushion, which floats, and which you are about to use as a shield instead.
sprite("seat_cushion", m("""
................
..kkkkkkkkkkkk..
.khhhhhhhhhhhhk.
.kbllllllllllbk.
.kbllllllllllbk.
.kbllllllllllbk.
.kbllllllllllbk.
.kbllllllllllbk.
.kbllllllllllbk.
.kbllllllllllbk.
.khhhhhhhhhhhhk.
..kkkkkkkkkkkk..
................
................
................
................
"""), {"k": "#151c28", "h": "#3b4a68", "b": "#28344c", "l": "#374764"})

# The safety card, in the seat pocket, unread and entirely correct.
sprite("safety_card", m("""
................
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kwrrrrrrrwk...
..kwwwwwwwwwk...
..kwbbwwbbwwk...
..kwbbwwbbwwk...
..kwwwwwwwwwk...
..kwbbbbbbbwk...
..kwwwwwwwwwk...
..kwbbbbwwwwk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
................
................
"""), {"k": "#2a2a2a", "w": "#e8e4d8", "r": "#c8362c", "b": "#4a6fa8"})

# A phone, on which you will film the thing instead of solving it.
sprite("phone", m("""
....kkkkkkkk....
....khhhhhhk....
....kwsssswk....
....kssssssk....
....kssssssk....
....kssssssk....
....kssssssk....
....kssssssk....
....kssssssk....
....kssssssk....
....kssssssk....
....kssssssk....
....khhhhhhk....
....kkkkkkkk....
................
................
"""), {"k": "#141416", "h": "#3a3d44", "s": "#4a7fb8", "w": "#a8d2f0"})

variant("power_bank", "phone", {"s": "#3f4650", "w": "#7ad86a", "h": "#22252a"})

# A laptop, open, which is a fuel load with a keyboard on it.
sprite("laptop", m("""
................
..kkkkkkkkkkkk..
..kssssssssssk..
..kswwwwwwwwsk..
..kswwwwwwwwsk..
..kswwwwwwwwsk..
..kssssssssssk..
..kkkkkkkkkkkk..
.kmmmmmmmmmmmmk.
.kmbbbbbbbbbbmk.
.kmbbbbbbbbbbmk.
.kmmmmmmmmmmmmk.
.kkkkkkkkkkkkkk.
................
................
................
"""), {"k": "#1a1c20", "s": "#4a4f58", "w": "#6f9fc8", "m": "#7d848f", "b": "#3a3f47"})

# The vape pen. The seat of the fire. Eleven grams, and it beat the aeroplane.
sprite("vape", m("""
................
................
................
..kkkkkkkkkkkk..
..kmmmmmmmmmmk..
.kkbbbbbbbbbbkk.
.khbbbbbbbbbbhk.
.kkbbbbbbbbbbkk.
..kmmmmmmmmmmk..
..kkkkkkkkkkkk..
.....kppk.......
.....kppk.......
......kk........
................
................
................
"""), {"k": "#141414", "m": "#3a3a42", "b": "#5b5f6b", "h": "#8e94a2", "p": "#6ad8c0"})

# Duct tape, the second most useful thing in the bag.
sprite("duct_tape", m("""
................
....kkkkkkkk....
...khhhhhhhhk...
..khgggggggghk..
..kgggkkkkgggk..
..kggk....kggk..
..kggk....kggk..
..kggk....kggk..
..kggk....kggk..
..kgggkkkkgggk..
..khgggggggghk..
...khhhhhhhhk...
....kkkkkkkk....
................
................
................
"""), {"k": "#1e2024", "h": "#a4aab2", "g": "#7a8088"})

# A tote bag of duty free, which is the loadout you will come to regret.
sprite("tote_bag", m("""
....kk....kk....
...k..k..k..k...
...k..k..k..k...
..kkkkkkkkkkkk..
..khhhhhhhhhhk..
..kbbbbbbbbbbk..
..kbbwwwwwwbbk..
..kbbwwwwwwbbk..
..kbbwwwwwwbbk..
..kbbbbbbbbbbk..
..kbbbbbbbbbbk..
..kbbbbbbbbbbk..
..kkkkkkkkkkkk..
................
................
................
"""), {"k": "#2a2018", "h": "#c8b08a", "b": "#a08c6a", "w": "#e2d4b8"})

# Duty-free perfume and hand sanitiser, both of which are, chemically, lighter fluid.
sprite("perfume", m("""
................
.......kk.......
......kbbk......
......kbbk......
.....kkkkkk.....
....kppppppk....
...kpppppppk....
...kppwwwppk....
...kppwwwppk....
...kpppppppk....
...kpppppppk....
...kpppppppk....
...kkkkkkkkk....
................
................
................
"""), {"k": "#3a2a30", "p": "#d88ab0", "w": "#f6d6e4", "b": "#c8a860"})

variant("sanitiser", "perfume", {"p": "#8ad0c8", "w": "#d6f2ee", "b": "#7a8890"})

# A miniature of spirits: one map, seven palettes, exactly like the science flasks.
sprite("mini_bottle", m("""
.......kk.......
.......kk.......
.......kk.......
......kddk......
.....kddddk.....
....kdccccdk....
....kdccccdk....
....kdcbbcdk....
....kdcbbcdk....
....kdccccdk....
....kdccccdk....
....kdccccdk....
....kdccccdk....
....kdddddk.....
.....kkkkk......
................
"""), {"k": "#241c14", "c": "#cfe0e8", "b": "#f0f6f8", "d": "#8fa4ae"})

for _name, (_c, _b, _d) in {
    "mini_gin":      ("#dfe9ec", "#ffffff", "#9fb0b6"),
    "mini_whisky":   ("#b5731c", "#e0a44c", "#7a4a10"),
    "mini_vodka":    ("#e4eef2", "#ffffff", "#a8b8bd"),
    "mini_rum":      ("#8a4a18", "#c07a3a", "#5a2e0e"),
    "mini_cognac":   ("#9a5a12", "#d08a30", "#66370a"),
    "mini_baileys":  ("#c9a878", "#e8d0aa", "#8e7350"),
    "mini_absinthe": ("#7ac83a", "#b8e878", "#4a8a18"),
}.items():
    variant(_name, "mini_bottle", {"c": _c, "b": _b, "d": _d})

# The trolley the miniatures came from, which is also a two-hundred-kilo rolling wall.
sprite("drink_cart", m("""
kkkkkkkkkkkkkkkk
khhhhhhhhhhhhhhk
khllllllllllllhk
khlmmmmmmmmmmlhk
khllllllllllllhk
kkkkkkkkkkkkkkkk
khlmmmmmmmmmmlhk
khllllllllllllhk
kkkkkkkkkkkkkkkk
khlmmmmmmmmmmlhk
khllllllllllllhk
kkkkkkkkkkkkkkkk
kdkkkkkkkkkkkkdk
kdd..........ddk
.d............d.
................
"""), {"k": "#2c313a", "h": "#b8c0cb", "l": "#8e97a3", "m": "#6c7480", "d": "#1a1c20"})

# The manual. Somebody on this aeroplane has read it and it is not you.
sprite("manual", m("""
................
..kkkkkkkkkkkk..
..krrrrrrrrrrk..
..krhhhhhhhhrk..
..krhwwwwwwhrk..
..krhwwwwwwhrk..
..krhwyyyywhrk..
..krhwwwwwwhrk..
..krhwwwwwwhrk..
..krhhhhhhhhrk..
..krrrrrrrrrrk..
..kkkkkkkkkkkk..
................
................
................
................
"""), {"k": "#1c1a18", "r": "#8a2a22", "h": "#d8d2c4", "w": "#f2eee2", "y": "#c8a02a"})

# A megaphone, brought aboard by somebody who had a plan.
sprite("megaphone", m("""
................
..........kkkk..
.........kwwwwk.
....kkkkkkwwwwk.
...krrrrrrwwwwk.
..krrrrrrrwwwwk.
..krhhhhhhwwwwk.
..krhhhhhhwwwwk.
..krrrrrrrwwwwk.
...krrrrrrwwwwk.
....kkkkkkwwwwk.
...kdk....kwwwk.
...kdk.....kkk..
...kdk..........
................
................
"""), {"k": "#1e1c1a", "r": "#c8362c", "h": "#e8746a", "w": "#c8ccd2", "d": "#3a3a3a"})

# A pet carrier with something in it that has been very quiet for an hour.
sprite("pet_carrier", m("""
................
....kkkkkkkk....
..kkbbbbbbbbkk..
..kbbbbbbbbbbk..
..kbkgkgkgkgbk..
..kbkgkgkgkgbk..
..kbkgkgkgkgbk..
..kbkgkgkgkgbk..
..kbkgkgkgkgbk..
..kbbbbbbbbbbk..
..kbbbbbbbbbbk..
..kkkkkkkkkkkk..
...k........k...
................
................
................
"""), {"k": "#1e1a16", "b": "#4a5a72", "g": "#8ad06a"})

# The iguana. It is emotional support, and it is not yours.
sprite("iguana", m("""
................
................
..gg............
.gkgg...........
.ggggggg........
..gggggggg......
...ggggggggg....
....gggggggggg..
.....g..g...ggg.
....g....g....gg
................
................
................
................
................
................
"""), {"g": "#5aa83a", "k": "#1a2a12"})

# The first aid kit and the defibrillator, both of which are for a different emergency.
sprite("first_aid", m("""
................
..kkkkkkkkkkkk..
..khhhhhhhhhhk..
..kwwwwwwwwwwk..
..kwwwwrrwwwwk..
..kwwwwrrwwwwk..
..kwwrrrrrrwwk..
..kwwrrrrrrwwk..
..kwwwwrrwwwwk..
..kwwwwrrwwwwk..
..kwwwwwwwwwwk..
..khhhhhhhhhhk..
..kkkkkkkkkkkk..
................
................
................
"""), {"k": "#2a2a2a", "h": "#b8b8b8", "w": "#e8e8e8", "r": "#c8322a"})

sprite("defib", m("""
................
..kkkkkkkkkkkk..
..kyyyyyyyyyyk..
..kykkkkkkkkyk..
..kykgggggggyk..
..kykgbbbbbgyk..
..kykgbwwwbgyk..
..kykgbbbbbgyk..
..kykgggggggyk..
..kykkkkkkkkyk..
..kyyyyyyyyyyk..
..kkkkkkkkkkkk..
................
................
................
................
"""), {"k": "#2a2418", "y": "#e8c02a", "g": "#3a3f46", "b": "#5a6470", "w": "#8ad86a"})

# A whistle, a torch, a rosary, a harmonica and a sock. The bottom of the bag.
sprite("whistle", m("""
................
................
.....kkkkkkk....
....khhhhhhhk...
...khsssssssk...
...kssskssssk...
...khsssssssk...
....khhhhhhhk...
.....kkkkkkk....
......k.........
.....k..........
....k...........
................
................
................
................
"""), {"k": "#2a2a2e", "h": "#c8ccd2", "s": "#9aa0a8"})

sprite("flashlight", m("""
................
...kkkk.........
..kyyyyk........
..kywwyk........
..kyyyyk........
..kkkkkkkkkkkk..
..kbbbbbbbbbbk..
..kbllllllllbk..
..kbllllllllbk..
..kbbbbbbbbbbk..
..kkkkkkkkkkkk..
................
................
................
................
................
"""), {"k": "#1a1c20", "y": "#f0d84a", "w": "#fffbe0", "b": "#3a4048", "l": "#5c6470"})

sprite("rosary", m("""
................
.....bbbbb......
....b.....b.....
...b.......b....
...b.......b....
....b.....b.....
.....b...b......
......b.b.......
.......b........
.......b........
......kkk.......
.......k........
.......k........
................
................
................
"""), {"b": "#8a6a3a", "k": "#c8a84a"})

sprite("harmonica", m("""
................
................
................
..kkkkkkkkkkkk..
..khhhhhhhhhhk..
..kmkmkmkmkmkk..
..kmkmkmkmkmkk..
..khhhhhhhhhhk..
..kkkkkkkkkkkk..
................
................
................
................
................
................
................
"""), {"k": "#1c1c1e", "h": "#c0c6cc", "m": "#7a8088"})

sprite("sock", m("""
................
....kkkk........
....kwwk........
....kwwk........
....kwwk........
....kwwk........
....kwwk........
....kwwkkkk.....
....kwwwwwwk....
....kwwwwwwk....
.....kkkkkkk....
................
................
................
................
................
"""), {"k": "#3a3a42", "w": "#c8ccd4"})

sprite("crossword", m("""
................
..kkkkkkkkkkkk..
..kwwwwwwwwwwk..
..kwkwkwwkwkwk..
..kwwwwwwwwwwk..
..kwkwwkwwwkwk..
..kwwwwwwwwwwk..
..kwkwkwwkwkwk..
..kwwwwwwwwwwk..
..kwwkwwwkwwwk..
..kwwwwwwwwwwk..
..kkkkkkkkkkkk..
................
................
................
................
"""), {"k": "#3a3a3a", "w": "#e6e2d6"})

sprite("headphones", m("""
................
.....kkkkkk.....
....k......k....
...k........k...
..k..........k..
..k..........k..
..kkk......kkk..
..kbbk....kbbk..
..kbbk....kbbk..
..kbbk....kbbk..
..kbbk....kbbk..
..kkkk....kkkk..
................
................
................
................
"""), {"k": "#26282e", "b": "#5a6270"})

sprite("pretzels", m("""
................
...kkkkkkkkkk...
...kyyyyyyyyk...
...kyddddddyk...
...kydbbbbdyk...
...kydbbbbdyk...
...kydbbbbdyk...
...kydbbbbdyk...
...kyddddddyk...
...kyyyyyyyyk...
...kkkkkkkkkk...
................
................
................
................
................
"""), {"k": "#3a2a12", "y": "#e0b040", "d": "#8a5a18", "b": "#c88a30"})

sprite("neck_pillow", m("""
................
....kkkkkkkk....
...khhhhhhhhk...
..khhkkkkkkhhk..
..khk......khk..
..khk......khk..
..khk......khk..
..khhk....khhk..
...khhk..khhk...
....khk..khk....
....kkk..kkk....
................
................
................
................
................
"""), {"k": "#2a2430", "h": "#8a7aa0"})

# The wet towel, which is the correct answer, and which nobody picks.
sprite("wet_towel", m("""
................
..kkkkkkkkkkkk..
..khhhhhhhhhhk..
..kbwbwbwbwbwk..
..kwbwbwbwbwbk..
..kbwbwbwbwbwk..
..kwbwbwbwbwbk..
..kbwbwbwbwbwk..
..khhhhhhhhhhk..
..kkkkkkkkkkkk..
................
................
................
................
................
................
"""), {"k": "#1c3038", "h": "#5a8fa8", "b": "#2f5e74", "w": "#417d96"})

# The interphone handset the crew talk to the flight deck on.
sprite("interphone", m("""
................
..kkkk....kkkk..
..khhk....khhk..
..khhkkkkkkhhk..
..khhhhhhhhhhk..
..khhhhhhhhhhk..
..kkkkkkkkkkkk..
......kkkk......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
................
................
................
"""), {"k": "#1e2026", "h": "#8a919c", "b": "#4a505a"})

# The call button, unlit and lit. You will press it more times than anyone in aviation history.
sprite("call_button", m("""
................
................
....kkkkkkkk....
...kmmmmmmmmk...
...kmllllllmk...
...kmlhhhhlmk...
...kmlhhhhlmk...
...kmllllllmk...
...kmmmmmmmmk...
....kkkkkkkk....
................
................
................
................
................
................
"""), {"k": "#1c1e22", "m": "#4a5058", "l": "#6e757e", "h": "#9aa2ac"})

variant("call_button_lit", "call_button", {"h": "#ffd83a", "l": "#c8a02a"})


# ---------------------------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------------------------

BANNER = ("// Generated by pixel-workshop/make_cabin_textures.py - do not edit by hand.\n"
          "// Every sprite is an ASCII map plus a palette; pixelmap.js draws these unchanged.\n")


def check():
    """Every map rectangular, every key coloured. A hole found here is not found in play."""
    problems = []
    for name, sp in SPRITES.items():
        widths = {len(r) for r in sp["rows"]}
        if len(widths) != 1:
            problems.append(f"{name}: ragged rows {sorted(widths)}")
        if len(sp["rows"]) > 16 or max(widths) > 16:
            problems.append(f"{name}: {max(widths)}x{len(sp['rows'])} is bigger than 16x16")
        used = {ch for row in sp["rows"] for ch in row if ch != "."}
        missing = used - set(sp["palette"])
        if missing:
            problems.append(f"{name}: no colour for {sorted(missing)}")
        for key, colour in sp["palette"].items():
            if not (isinstance(colour, str) and len(colour) == 7 and colour[0] == "#"
                    and all(c in "0123456789abcdefABCDEF" for c in colour[1:])):
                problems.append(f"{name}: {key} is not a hex colour ({colour!r})")
    return problems


def write_preview(path):
    from PIL import Image
    cols, cell = 12, 18
    names = sorted(SPRITES)
    rows = (len(names) + cols - 1) // cols
    img = Image.new("RGBA", (cols * cell, rows * cell), (40, 42, 48, 255))
    px = img.load()
    for i, name in enumerate(names):
        ox, oy = (i % cols) * cell + 1, (i // cols) * cell + 1
        sp = SPRITES[name]
        for y, row in enumerate(sp["rows"]):
            for x, ch in enumerate(row):
                if ch == ".":
                    continue
                c = sp["palette"].get(ch, "#ff00ff").lstrip("#")
                px[ox + x, oy + y] = (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16), 255)
    img.resize((img.width * 3, img.height * 3), Image.NEAREST).save(path)


def main():
    problems = check()
    if problems:
        for p in problems:
            print("  !", p)
        print(f"{len(problems)} problem(s); nothing written.")
        return 1

    os.makedirs(OUT_DIR, exist_ok=True)
    blob = json.dumps(SPRITES, separators=(",", ":"), sort_keys=True)
    js = os.path.join(OUT_DIR, "cabin-sprites.js")
    with open(js, "w", encoding="utf-8") as fh:
        fh.write(BANNER)
        fh.write("window.PRS_ART = window.PRS_ART || {};\n")
        fh.write("window.PRS_ART.cabin = ")
        fh.write(blob)
        fh.write(";\n")
    print(f"{len(SPRITES)} sprites -> {os.path.relpath(js, ROOT)}")

    if "--json" in sys.argv:
        path = os.path.join(OUT_DIR, "cabin-sprites.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(SPRITES, fh, indent=1, sort_keys=True)
        print(f"                 -> {os.path.relpath(path, ROOT)}")

    if "--preview" in sys.argv:
        path = os.path.join(HERE, "cabin-preview.png")
        write_preview(path)
        print(f"                 -> {os.path.relpath(path, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
